# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mjzheng/Documents/mj_git/oc-sample/IDbg/IDbg/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mjzheng/Documents/mj_git/oc-sample/IDbg/IDbg/version_config.h.in))

/Users/mjzheng/Documents/mj_git/oc-sample/IDbg/project/ios/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.18.4/bin/cmake -H/Users/mjzheng/Documents/mj_git/oc-sample/IDbg -B/Users/mjzheng/Documents/mj_git/oc-sample/IDbg/project/ios
